#!/bin/bash

NAME='a0'

for cell in  6.0 6.2 6.4 6.6 6.8 7.0 7.2 7.4 7.6 7.8 8.0
do

    grep '!' $NAME.$cell.out > data.dat
    awk '{print $5}' data.dat >> energy.dat
    read E1 < energy.dat

    cat >> acell.dat<<!
    $cell $E1
    !

    rm -f data.dat
    rm -f energy.dat
done
